spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: '{cipher}AQB0Hvaz2Gosv8cwKOq+N2Z3he8QG6LLE8eZKFU7um2tKBztMYxvyAoxwLex6B8aqT3nPz+OhWWtGC2WEWaXCvXD53pqoi7gpmTIvq0JKvbvANg374+pzKNNsIBTngSF61FUGjPHsO8z0iNNXqjxeNrOeHBmsYn+/DAIOJjBDb2HzXukVMe6DpbLMpbOW9lXMXgAqehN93k4Ju5CXFeF6kg5bY4ysJJAEIHPdTy2HYtRsivABCjI1/GxVepP+5cKGmKIUurDkw/aiv5alYofSx38jXAWmGcYa9zfllD579cZOL5QWkOxixDIEcMxt4toe2++SLCcCDf7OcWWicL3l9tUZjeejQRIlEAxGGJZ1LHLI14T607O+QwUkSlK44CVfwg='

# 공통으로 사용되는 property는 application.yml에 선언.
# token:
#   expiration_time: 86400000
#   secret: '{cipher}AQAu4mnp+tRB554f+5FKAcCtOWTuvjEjj9AAYOV/J/Brc8m7Rs+ADDGxeK7FgGPFUOc9XjqLED2OtgvqESp6XCo5YrZfZU22N6pw6rcMsEI+HURPz0/PaEmUL20B8eMe/jus8lslsAYnot0LZul8Q127hLb1PS4nkXMiP9Ivx/DLQQcJtjzKlWwMZlhKkmZkXyB8AymrLq8DvKgpnm+XGR0N12h8myB/s96a5XQgKLK73TgyCwQsOGf9INll7Jo1fMWhXaFFkknrdHKiQTC1utLZy9W/WBwiIOfO0iPESadznCxKMZ7fI2aVqROilbdYwPT6jHBhMzbnkuzJAIo9QSdQBewg4b7ByCX4t6OV39pX4wSxfxpy1UQMWnZOFlWpp6h9rxJ4g7HgbZyNp47mtwUD'

gateway:
  ip: 172.30.1.7